// Copyright © 2022 Michael Thompson
// SPDX-License-Identifier: GPL-2.0-or-later

Layercake configuration
=======================

Layercake operates perfectly well without a configuration file.  The user may override any or
all of the default settings via configuration files.  Some settings may also be overridden by
environment variables or the command line.

== Default configuration

Base directory: `/var/lib/layercake`::  Root of directory tree on which Layercake operates.
Contains the Layers and Export directories and the prototype layer-configuration file for
base layers. +
Configuration-file key BASEPATH, environment variable LAYERROOT
Layers directory: `layers`::  Name of directory relative to the Base directory that contains
all layer directories. +
Configuration-file key LAYERS
Build directory: `build`::  Name of directory relative to its respective layer directory that
acts as the build root for the layer. +
Configuration-file key BUILDROOT
Binary-package directory: `packages`::  Name of directory relative to its respective layer
directory to be bind-mounted to the binary-packages directory in the build root (generally
`/var/cache/binpkgs`).  Layercake generates this directory if the layer's configuration
specifies that the directory be mounted. +
Configuration-file key BINPKGS
Generated-files directory: `generated`::  Name of directory relative to its respective layer
directory to contain files generated from or about build root such as stage tarballs
generated by _stagemaker_.  Layercake never generates these directories. +
Configuration-file key GENERATED_FILES
OverlayFS Work directory: `overlayfs/workdir`::  Name of directory relative to its respective
layer directory of the overlayfs work directory for the layer.  Layercake generates this
directory only for derived layers. +
Configuration-file key WORKDIR
OverlayFS Upper directory: `overlayfs/upperdir`::  Name of directory relative to its
respective layer directory of the overlayfs upper directory for the layer.  Layercake
generates this directory only for derived layers. +
Configuration-file key UPPERDIR
Exports directory: `export`::  Name of directory relative to the Base directory to hold a
tree for export of packages as described in the Binary Package Guide.  Layout of the
directory permits export of generated files by the same means as for package files. +
Configuration-file key EXPORTS
Binary-package-export directory: `packages`:: Name of directory relative to Exports
directory to contain symlinks to binary-package directories for each layer.  Layercake
delays creation of these symlinks until the layer is mounted. +
Configuration-file key EXPORT_BINPKGS
Generated-file-export directory: `generated`:: Name of directory relative to Exports
directory to contain symlinks to layers' generated files.  Layercake generates these
symlinks at mount time only if the layer contains a corresponding Generated-files
directory.
Configuration-file key EXPORT_GENERATED_FILES
Chroot exec: `/usr/bin/chroot`:: Path of the system's _chroot_ executable. +
Configuration-file key CHROOT_EXEC

A configuration file with these lines yields these defaults:

---------------------
BASEPATH = /var/lib/layercake
LAYERS = layers
BUILDROOT = build
BINPKGS = packages
GENERATED_FILES = generated
WORKDIR = overlayfs/workdir
UPPERDIR = overlayfs/upperdir
EXPORTS = export
EXPORT_BINPKGS = packages
EXPORT_GENERATED_FILES = generated
CHROOTEXEC = /usr/bin/chroot
---------------------

== Configuration-file selection

Layercake takes its configuration from the first of these sources it encounters:

- file named in the *-config* command-line switch
- file named in the `LAYERCONF` environment variable
- _.layercake_ file in the user's home directory
- _layercake.conf_ file in the _etc/_ directory parallel to the directory containing the
Layercake executable (e.g. if the executable is `/usr/local/bin/layercake`, Layercake will
look for `/usr/local/etc/layercake.conf`)
- defaults contained in the executable

== Configuration-file chaining

A configuration file may indicate that another is to be loaded by including the `CONFIGFILE`
key.  This could be useful in a setup with a second Layercake root for testing.  Assuming that
the second root should have the same configuration as the first except for the `BASEPATH`, the
second configuration file could declare only the proper `BASEPATH` and then link to the first
configuration file for the rest of the custom settings.  This works because the first value
encountered for any given key takes precedence.  Layercake checks for file-load loops.

--------------
BASEPATH = /var/lib/secondpath
CONFIGFILE = /usr/local/etc/layercake.conf
--------------

== Base-path override

The base-path parameter has two additional overrides.  The value of the LAYERROOT environment
variable overrides any value of the `BASEPATH` key from the configuration files and the
*-basepath* command-line switch overrides both.

