Setting up the Layercake environment
====================================

Concepts:

- Each build-root directory and its associated files and directories are grouped together
into a directory called a _layer directory_.
- Layer directories in turn reside in a single directory where Layercake identifies each
layer by its directory name.  This is the Layers directory.
- Parallel to the Layers directory is a directory of exports which serves as the document
root for a web or file server.  This Exports directory contains directories and symlinks
which Layercake manages plus other entries which the user may insert according to need.
- Normally the Layers and Exports directories are children of a base directory.  This
arrangement gives a Layercake installation a very useful attribute:  all of its
manipulations are confined to a single directory tree.

Names for most of the relevant directories may be set via a configuration file (see the
link:layercake_config.adoc[Layercake configuration] page for details).  Most installations
should not need one.

Configurations which place the Layers or Exports directories outside the base path are
possible but discouraged.

== 1. Set the Layercake base path

The default configuration uses `/var/lib/layercake` as the base directory.  If this is
suitable, skip to step 2 to set the base-path directory ready to receive layers.

There are several ways to specify a different directory, but here we mention only one:  a
`layercake.conf` configuration file in the `etc` directory that is a sibling to the
directory which contains the layercake executable.  (So if the executable is in
`/usr/local/bin`, Layercake will look for  `/usr/local/etc/layercake.conf`)

Insert a line similar to this:

---------
BASEPATH = /other/base/path
---------

== 2. Generate the base directory

Issue the command

---------
layercake status
---------

to ensure that nothing is already set up.  You should see a message like this

---------
Missing item(s):
  base directory /var/lib/layercake
  base directory /var/lib/layercake/layers
  base directory /var/lib/layercake/export
  default layer configuration /var/lib/layercake/default_layerconfig.skel
Cannot proceed unless all exist
---------

This message also gives an indication of whether the configuration is correct:  the base
path should be as you configured it.

To generate the needed the directories, issue this command:

---------
layercake init
---------

Now the _layercake status_ command should now give the message

---------
Base directories set up OK at /var/lib/layercake
---------

== 3. Verify default mounts

Every layer directory contains a `layerconfig` file that indicates the mounts and symlinks
which the Layercake _mount_ and _chroot_ commands create as necessary.  At the time the user
first issues the _layercake add_ command to generate a base (i.e. non-derived) layer,
Layercake creates `layerconfig` using the file `default_layercake.skel` in the Base Path
directory as a pattern.

It is helpful, therefore, to be sure that `default_layerconfig.skel` is set up for the
typical use case.

If your host and target systems follow the pattern established in the stage tarballs Gentoo
has distributed for the past few years (Portage tree and overlays in subdirectories of
`/var/db/repos`, distribution tarballs in `/var/cache/distfiles`, and binary packages in 
`/var/cache/binpkgs`, and you wish to let your layers take advantage of shared Ebuilds and
source tarballs, the initial `default_layerconfig.skel` will do what you need.  If not, look
to the link:layercake_layerconfig.adoc[layer-configuration] page for detailed
instructions.

[NOTE]
On non-Gentoo host systems, the _emerge_ command is unavailable outside of build chroots.
There are two options for handling the directory trees for the Portage ebuilds and
distribution tarballs:  either with ordinary (non-mountpoint) directories in the build root
or separate hosts directories on the host.  For the former approach, remove the
`default_layerconfig.skel` lines for the `/var/db/repos` and `/var/cache/binpkgs` imports.
For the latter approach, create empty directories on the host and edit
`default_layerconfig.skel` as needed.  On most Linux distros, you should be able to create
empty `/var/db/repos` and `/var/cache/binpkgs` directories and simply leave the configuration
file alone. +
 +
In either event, you will need to follow the _emerge-webrsync_ and _emerge --sync_ steps as
shown in the Gentoo Handbook.  Be aware that running _emerge --sync_ in the build root will
make it so that the layer can't be unmounted without killing the background process that
_emerge --sync_ creates.

== 4. Set up web/file server

The link:https://wiki.gentoo.org/wiki/Binary_package_guide#Setting_up_a_binary_package_host[
"Setting up a binary package host" section of the Binary Package Guide] describes setting up
the service of package and generated files using via HTTP, SSH, or NFS.  The directory to
serve is the Export directory (by default `/var/lib/layercake/export`).  Be sure the server
is configured to follow symlinks.

