Layercake layer configuration
=============================

The `layerconfig` file in each layer directory is a text file of directives, one per line.
There are three types of directive:

- The *base* directive, present only in derived layers, indicates the lower layer upon which
the layer will be _overlayfs_ mounted.  Layercake's _add_, _rebase_, and _rename_ commands
alter this directive upon making the proper safety checks.  Users should refrain from editing
this manually.
- An *import* directive indicates a mount from the host system to a mountpoint within the
build root.
- An *export* directive indicates a symlink in an export directory to a file or directory in
a layer.

=== *import* directive

This directive takes three arguments:

- The mount type as is valid for the *mount*(2) system call.  In practice this is only
"rbind" or "proc".
- The host path of the source of the mount.  This must be either an absolute path or a name
prefixed by a special symbol:
* `pass:[$$self/]` for a path relative to the layer's layer directory
* `pass:[$$base/]` for a path relative to the layer directory of the layer's base layer
- The mountpoint path within the build root.

(The `pass:[$$]` prefix for these symbols is to allow for forward compatability with
user-defined variables in a later version of Layercake.)

The file `default_layerconfig.skel` in the Layercake Base directory provides the skeleton
for the `layerconfig` file of new base layers.  The contents of this file as generated by the
_layercake init_ command provides a helpful illustration of the possibilities of the *import*
directive..

-----------
import rbind /dev /dev
import proc /proc /proc
import rbind /sys /sys
import rbind /var/db/repos /var/db/repos
import rbind /var/cache/distfiles /var/cache/distfiles
import rbind $$base/packages /var/cache/binpkgs
-----------

The first three lines control the pseudo-filesystem entries required for the chroot: `/dev`,
`/proc`, and `/sys`.  Adding another line for an rbind mount on `\run` would silence Portage
warnings about `/run` not being a mountpoint.

The next two lines indicate the sharing of host-system Portage directories.  The first of
the mounts shown binds the host `/var/db/repos` to the same directory in the build root.
This captures the Portage tree and any overlay repos a single mount.  The second mount
lets the build root share a systemwide common source-tarball directory.

The last line bears more explanation.  It indicates a mount of the `packages` directory in
the layer's base layer to the layer's binary-package directory.  The figure below illustrates
this pattern using a base layer and layers derived from it.

--------------------
  Layers
  ======
  rosebud/                 (base layer)
     build/                    (build root of rosebud)
        var/cache/binpkgs      (rosebud/packages mounts here)
     packages/                 (export symlink points here)

  notebook/                (layer derived from rosebud)
     build/                    (build root of notebook)
        var/cache/binpkgs      (rosebud/packages mounts here)
                               (this layer has no packages/ directory)

  t400/                    (layer derived from notebook)
     build/                    (build root of t400)
        var/cache/binpkgs      (rosebud/packages mounts here)
                               (this layer has no packages/ directory)
--------------------

==== Why use a common packages/ directory for all layers with a common base?

It would be possible to set up separate package-export symlinks for each layer; that is
indeed what version 1 of Layercake did.  Experience shows that the approach has a major flaw:
incorrect information in the derived layers' binary-package databases accumulates over time.
This comes about because the binary-package system relies on a metadata file (called
`Packages`) in the `binpkgs` directory.  On first use of a derived layer, everything is
happy:  the `Packages` file bubbles up from the base layer with the full set of correct
metadata.  Emerges in the derived layer modify the file with updated information, and things
are still OK.

Problems happen at the next world update.  When Portage in the derived layer added binary
packages in its first run, it updated the `Packages` file.  This editing caused _overlayfs_
to give the layer its own private copy of the file that no longer stays in sync with the
`Packages` file from the base layer.  Now a world update in the base layer updates the
installed package database ("VDB") so that updates to installed packages are visible in
derived layers, but since the `Packages` file is not updated, target machines using
derived layers *do not* see the updates.  They would have to do full builds of all the
updates--defeating the point of having a build host!

The newer approach makes it so that there is only a single `Packages` file for all layer's
sharing a common base layer (a base layer is counted as its own base layer).  With Portage
in all the layers configured with the _binpkg-multi-instance_ feature enabled, all the
updates to the file preserve all the separate configurations of the packages from each
layer.

There is a second benefit.  Since the layer-mount operation automatically creates missing
rbind-source directories if they are children of the layer directory, Layercake generates the
base `packages` directory automatically.  Also, since the name `packages` is the same as the
value of the *BINPKGS* key in the Layercake configuration, Layercake creates the export
symlink automatically at layer-mount time.


=== *export* directive

This directive takes three arguments following in the pattern of the *import* directive:

- The mount type of "symlink".  No other type is legal.
- The source of the data to export--thus the symlink target:  a path within the layer
directory
- Indication of the directory to hold the symlink.  Must be one of
* `pass:[$$package_export]` makes an entry in `export/packages`
* `pass:[$$file_export]` makes an entry in `export/generated`

In most cases, it is not be necessary to insert explicit *export* directives in the
`layerconfig` file.  When the `packages` and `generated` directories are present in the
layer directory, Layercake acts as if these exports were present:

------------
export symlink /packages $$package_exports
export symlink /generated $$file_export
------------

If the user decides to forgo the use of derived layers (possibly because _overlayfs_ mounts
are unavailable), it is possible to skip the use of the `packages` directory.  In this case,
remove the import of `pass:[$$base/packages]` and add this *export* directive:

------------
export symlink /build/var/cache/binpkgs $$package_exports
------------


