// Copyright © 2022 Michael Thompson
// SPDX-License-Identifier: GPL-2.0-or-later

== Basic usage patterns

These steps assume the user has configured and initialized the Layercake installation in
an operational Gentoo host environment.  Many configurations are possible.  For details
about the setup, see link:layercake_setup.adoc[Setting up the Layercake environment].

These examples assume further that the build host has the name "builder" and that we have set
up a web server that listens on port 1000 to serve documents from the Layercake exports
directory.


=== Create, populate, and use a base layer

We use the term _base layer_ to denote a layer built up fully from a stage tarball according
to instructions in the Gentoo Handbook.

In this example we use "rosebud" as the name of the layer and intend to build the layer with
a USE-flag setup to match an already-deployed target.  Start with this command:

--------------------
layercake add rosebud
--------------------

This generates the layer along with its build-root directory and `layerconfig` file.  Note
the basic calling form of Layercake:  the first positional paramter is the name of a command;
additional positional parameters are arguments.

Whereas the Handbook has you create, mount, and chdir to a new root filesystem, use this
command instead:

--------------------
layercake shell rosebud
--------------------

This opens a shell in the build root directory.  Here is where you select, download, and
install a stage tarball and set things up in in preparation for the chroot.  You can save
time by copying Portage files from your existing target.  Don't forget to copy
`/etc/resolv.conf` from the host system.

In most cases, there is no need to edit the link:doc/layercake_layerconfig.adoc[layer's
configuration file].  If there is, it is easily reached at this point because it is in the
parent directory of the build root.

When setting up _make.conf_, be sure to add the _buildpkg_ and _binpkg-multi-instance_
features to the FEATURES variable.  (You may omit _binpkg-multi-instance_ if you will
never use OverlayFS mounts.)

Once the build root is set up with the basic configuration, exit the current shell and
enter the chroot with this command:

--------------------
layercake chroot rosebud
--------------------

If you get a message about a mountpoint directory not existing, fix the problem and try the
_layercake chroot_ again.

Of note:  for these examples, we assume we are using the host system's Portage tree and
overlays at the directory `/var/db/repos`.  Since this is the default configuration and
the _layercake chroot_ command makes the mounts automatically, there is no need to download
the initial Portage tree or to do _emerge sync_ within the chroot.

As to steps the Gentoo Handbook gives at this point

- Skip mounting the boot partition
- Skip _emerge-webrsync_ and _emerge --sync_ unless running on a non-Gentoo build host
- Select the desired profile, which might well be a custom profile
- Set up the USE variables
- Set up the time zone if desired
- Set up the locale
- Skip setting up the kernel and initramfs but emerge firmware if the targets will need it
- Skip setup steps for network, fstab, root password, and bootloader

The layer is fully accessible from other Bash prompts.  There is no problem at all
for a user to issue a _layercake chroot_ command to have an additional chroot into the
layer or to issue _layercake shell_ to switch to the layer's build root while still keeping
access to the full host filesystem.  The latter can be quite helpful if your editor of choice
is not _nano_.

Build all the packages your target will need.  Once done, you may exit the chroot.  Note
that this action never unmounts anything.  To unmount a layer (short of rebooting or
unmounting by hand!) issue the _layercake umount_ command:

--------------------
layercake umount rosebud
--------------------

Note that it is rarely necessary to unmount a layer.

==== On the target host

Assuming that we have set up the layer with USE flags and _march_ to match an existing target
system and then built a full set of packages for it, we can set up the target to use the
build root by setting the following entries in the target's make.conf:

- FEATURES="getbinpkg"
- PORTAGE_BINHOST="http://builder:1000/packages/rosebud"

Now an _emerge world_ should pick up all its new packages from the build host.

=== Create and use a child (derived) layer

This is much simpler than setting up a base layer.  Here we assume the derived layer,
called "notebook", has a different set of processor flags than does rosebud.

--------------------
layercake add notebook rosebud
--------------------

This form of the _add_ command specifies the base layer ("rosebud") for the new layer
("notebook").  Since this is not a base layer, we can go directly to the chroot:

--------------------
layercake chroot notebook
--------------------

Edit the Portage configuration as necessary and build according to the new configuration
with the confidence that the base layer remains unaltered.

This time we need to set up a new machine.  We could start with a recent stage3 file on
that machine, but we would likely be faced with rebuilding packages on that machine
since some of the packages in the @system set would now have different USE flags.  We
avoid this problem by using _stagemaker_ to generate a stage3 tarball that matches the
build environment.

Since we write the new stage tarball to a directory outside the build root (and also because
_stagemaker_ itself is not part of the build root), we cannot stay in the chroot to generate
the stage.  Exit the chroot and issue these commands to generate the stage tarball:

--------------------
layercake shell notebook
mkdir ../generated
layercake mount notebook
stagemaker -generate -o ../generated/stage.tar.gz
--------------------

The _layercake shell_ command takes us to the build directory, the _mkdir_ command creates
the directory to hold the stage file, the _layercake mount_ command ensures the needed
symlink is visible to the web server, and the _stagemaker_ command generates the actual stage
tarball.

Note that while Stagemaker is designed to operate with an arbitrary root directory and has no
requirement to be confined to a chroot, nothing keeps it from working in a chroot with
the *-root /* option.  It is a static executable with no configuration file needed.

==== On the target host

Now as we set up the new target, we download the stage tarball with

--------------------
wget http://builder:1000/generated/notebook/stage.tar.gz
tar xzpf stage.tar.gz --xattrs-include='*.*'
--------------------

or, if you are more adventurous,

--------------------
curl http://builder:1000/generated/notebook/stage.tar.gz | tar xzp --xattrs-include='*.*'
--------------------

The *--xattrs-include* switch is still required for Stagemaker-generated tarballs in order to
extract file capabilities, but *--numeric-owner* is not because Stagemaker does not store
user or group names.

Stage tarballs that come from the Gentoo upstream contain vanilla copies of all files in
`/bin`, `/etc`, `/usr`, and `/var` as generated from the ebuilds in the system set plus
vanilla `/etc/portage` settings.  By contrast, the stagemaker utility copies over any edits
made to these files in the build root.  This is a handy way to propate settings you will use
all the time, but there are caveats as regards the Portage files `/etc/portage/make.conf` and
`/var/lib/portage/world`.

In make.conf on the target machine, be sure to remove _buildpkg_ and _binpkg-multi-instance_
from the FEATURES variable and add _getbinpkg_. Add a PORTAGE_BINHOST variable to point to
your build host.

- FEATURES="getbinpkg"
- PORTAGE_BINHOST="http://builder:1000/packages/rosebud"

The world file in the generated stage tarball includes the full set of entries in the
build root's `/var/lib/portage/world`.  Since you may want only a subset of these packages on
the target machine, so be sure to edit out any such lines before emerging world.  Edit as
needed and then do the world update.

Now you may finish the setup as the Gentoo Handbook instructs.


