// Copyright © 2022 Michael Thompson
// SPDX-License-Identifier: GPL-2.0-or-later

STAGEMAKER(1)
============
:doctype: manpage


NAME
----
stagemaker - generates Gentoo stage tarballs from installed Gentoo systems


SYNOPSIS
--------
*stagemaker -list* 'list-type' ['options']

*stagemaker -generate* ['options']

*stagemaker -help*

*stagemaker -version*


DESCRIPTION
-----------
Stagemaker is a tool that generates Gentoo stage tarballs from packages installed in a
build root of a binary-build host (managed by Layercake or not).

Motivation:  Package sets built up on a package host typically include @system-set packages
that had to be rebuilt to accomodate the target USE-flag set.  This mismatch between the
binary USE-flag settings and the ones in vanilla stage3 tarballs can make setting up new
target machines using such tarballs a surprisingly difficult experience:  the _emerge_
command makes many complaints about dependency mismatches between binary packages and the
installed set.  The user can try to force _emerge_ to accept mismatches if it can, but in
may cases packages have to be rebuilt anyway.

Enter Stagemaker.  Stagemaker generates stage tarballs from existing build roots, eliminating
these mismatches.

Stagemaker differs in several respects from _catalyst_, the tool which generates official
stage tarballs.  Whereas _catalyst_ assembles a system from scratch (except for using an
existing stage tarball for its miscellaneous parts) and builds everything in steps from
stage 1 to stage 3 or 4, Stagemaker does no emerging at all.  Stagemaker starts from a
populated build root and its installed-package database ("VDB").  Apart from discovering
the contents of the @system set, Stagemaker makes no reference to the Portage repo.  It
obtains all the dependency information it needs from the VDB.

The user may customize the tarball:

- Add package atoms beyond the @system set.  These may include needed tools including
editors and also blocker atoms.
- Edit files which belong to packages to be included in the tarball.  Stagemaker writes
these files to the tarball along with their edits.
- Add additional files, directores, symlinks, or device nodes.
- Modify or remove files, directories, symlinks, or device nodes that would ordinarily be
written.


MAIN ACTIONS
------------
The command line must include exactly one of these switches.  Note that these and all other
switches may begin with either one or two hyphens.

*-list* `set`::
Display a listing of the packages or files from the specified set:
[horizontal]
*system*::: the @system set for the profile
*installed*::: all installed packages (the @installed set)
*stage*::: packages/files to include in the stage tarball as a result of dependency resolution
and file inclusion/exclusion

*-generate*::
Generate a stage tarball.  Writes to stdout unless the *-o* option is specified.

*-help*::
Show a help message.

*-version*::
Show the program version.


OPTIONAL SWITCHES
-----------------
*-root* 'path'::
Specify the path of the build-root directory.  The default is the current directory.

*-profile* 'path'::
Specify the path of the profile directory for identifying the @system set.  Defaults to
`etc/portage/make.profile` in the build root.

*-atoms* 'list'::
Space-separated list of package atoms to add to the set to resolve.  Atoms may include
Gentoo-standard relative-version and/or blocker prefixes.  Atoms may omit the category
when the base package name is unambiguous in the set of installed packages.

*-atomsfile* 'filename'::
Like the *-atoms* switch except that atoms are read from the specified file, the contents
of which have one atom per line as does the `/var/lib/portage/world` file

*-addfiles* 'filename'::
Indicates a file which specifies filesystem entries to add to or remove from the
generated tarball.  See ADD-FILES FORMAT.

*-recipe* 'filename'::
Indicates a file which specifies multiple configuration options in a single place.  See
RECIPE-FILE FORMAT.

*-nobdeps*::
Exclude build dependencies (dependencies listed under `BDEPEND`) from the stage tarball.
This may be necessary when Portage somehow managed to build packages without needing
the specified build dependencies.  (This is observed to happen!)

*-novdb*::
Exclude the VDB database from the stage tarball.  This is the installed package database
that is required in normal Gentoo systems.  This may be useful if setting up a very minimal
system that never would have Portage operate on it.

*-emptydev*::
Leave the generated `/dev` directory empty.  Stage tarballs normally populate `/dev` with
static device notes; this switch omits them.  Caution:  omitting these device nodes results
in an un-bootable system unless these two conditions obtain: 1) the kernel is configured
for _devtmpfs_, and 2) the boot loader/initramfs does not use *switch_root*(8).

*-files*:: 
Cause *-list* to list files instead of packages.

*-filesbypackage*::
Cuase *-list* to show files grouped by package.

*-o* `path`::
Specify output path.  When generating a stage file, the filename extension determines
the file-compression mode.

*-compress* 'method'::
Compress the output tarball.  Overrides any setting inferred via the *-o* switch.
Methods available: *gzip*, *bzip2*, *xz*, or *none*.  Compression requires that the system
have the needed compression filter available in the `$PATH`. +
 +
Switch is required when generating a tarball and the *-o* option is not given or the filename
extension for the *-o* switch cannot be recognized.


ADD-FILES FORMAT
----------------
Non-comment, non-blank lines have the format 'type' 'name' 'options'

The set of available or required options depends on the entry type.  The 'type' and 'name'
arguments are required; the 'name' indicates the name of the entry in the generated tarball.
Options are in the format _key=value_ with no spaces between the key and the value.  If
names contains spaces, backslashed, or begin with quote marks, they must be escaped with
backslashes and/or quotes.  If an option value contains spaces, escaping is the same except
that using quotes requires that both key and value be in quotes.

These are the legal entry types.

*file*::
Normal file.  In the absence of the *src=* option, contents of the file are taken from the
file in the build root.  Accepts the *mod=*, *uid=*, *gid=*, *src=*, and *absent=* options.

*dir*::
Directory.  Creates a directory in the stage tarball even if it is not present in the
build root.  Accepts the *mod=*, *gid=*, *uid=*, and *absent=* options.

*node*::
Device node.  Takes the type and address information from the *dev=* option or the device
node specified by the *src=* option.  In the absence of these two, this infomation is read
from the corresponding device node in the build root.  Accepts the *mod=*, *uid=*, *gid=*,
*dev=*, *src=*, and *absent=* options.

*symlink*::
Symbolic link.  Writes a symbolic link using a target specified by the *targ=* option or from
a symbolic link at the same path in the build root.  Accepts the *targ=* and *absent=*
options.

*tbd*::
Undetermined type.  Creates a file, directory, or symlink in the tarball according to the
type of the existing object in the filesystem.  This accounts for cases where, for example,
the user substituted a symlink for a regular file.  Files owned by packages are written to
the tarball using the *tbd* type.  Accepts the *absent=* option.

*omit*::
Omit file.  Indicates that the stage tarball is to omit the file, directory, symlink, or
device node that would normally be written.

Observe that there is no 'type' listed here for hard links.  Stagemaker stats every file to
be added and writes hardlink entries to the stage tarball for files that share an inode
with a file already written.

The 'name' argument indicates the name of the directory entry to be inserted into the stage
tarball.  The base part of a name may contain an asterisk, in which case special rules apply
for globbing.  If 'type' is *dir*, globbing applies recursively to that directory.  For other
entry types, globbing is not recursive.  The *src=* option is unavailable when globbing is
specified.

Asterisks in the base part of names must be escaped with backslashes even if the names are
wrapped in quotes.

Option keywords are as follows:

*mod=*::
Permission bits of the file mode.  Value may take the forms the *chmod*(1) command allows:
an octal mask or a string of mode-setting characters.  If the contents of the entry are
read from the 'name' argument or the *src=* option, a string of mode-setting characters
serves to modify the file mode of the indicated source.

*gid=*::
Integer group ID to apply to the file.

*uid=*::
Integer user ID to apply to the file.

*src=*::
Name of source file, directory or device node to use as source data for the entry to be
created.  Recursively copies source-directory entries if name is of a directory.  Names are
relative to the current directory; absolute paths specify paths relative to the process' root
directory.  Prefix the path with `$$stageroot` to indicate paths relative to the build root.

*dev=*::
Type and major/minor numbers of the device node.  Value is in the format tMAJOR:MINOR, where
t is either `b` (block) or `c` (character) and MAJOR and MINOR are integers.

*targ=*::
Target of the symbolic link.  May be relative or absolute.  Absolute paths are relative to
the root of target system; relative paths are relative to the symlink.

*absent=skip*::
Excusable absence:  ignore the entry without error if the named object does not exist.


ADD-FILES EXAMPLE
-----------------

   # Normal file with permissions and contents as they are in the source tree
   file /etc/portage/package.use

   # Normal file with contents taken from a file outside of the source tree
   file /etc/vim/vimrc src=/etc/vim/vimrc

   # Normal file with a space in the name wrapped in quote marks
   file "/usr/lib/python3.7/site-packages/setuptools/script (dev).tmpl"

   # Normal file with same name with backslash escape
   file /usr/lib/python3.7/site-packages/setuptools/script\ (dev).tmpl

   # Normal file which may be absent from the actual filesystem without causing fatal error
   file /etc/udev/rules.d/70-persistent-net.rules absent=skip

   # Zero-length normal file
   file /etc/udev/rules.d/70-persistent-net.rules src=/dev/null

   # All files in directory
   file /etc/portage/*

   # Filename containing an asterisk
   file /home/user/some\*name

   # Directory
   dir /dev

   # Directory in which contents are taken from a separate directory in the source tree
   dir /etc/portage src=$$stageroot/home/user/portage uid=0:0

   # Device nodes
   node /dev/sda dev=b8:0 uid=6
   node /dev/tty7 dev=c4:7 uid=5

   # Symbolic link
   symlink /usr/portage targ=/var/db/repos/gentoo

   # Filesystem entry of type to be determined at run time; ignore if absent
   tbd /usr/tmp absent=skip


RECIPE-FILE FORMAT
------------------
Non-blank, non-comment lines have the format _directive <arguments>_

*root* 'path'::
Specify a build-root path.  The *-root* command-line switch overrides this.

*profile* 'path'::
Specify a profile directory to find the @system set.  The *-profile* command-line switch
overrides this.

*atoms* 'list'::
Specify atoms in addition to any specified via the command line.

*atomsfile* 'filename'::
Specify an (additional) file of atoms to add.

*addfiles* 'filename'::
Specify an (additional) add-files file.

*compress* 'mode'::
Specify a compression mode.  The *-o* and *-compress* command-line switches override this.

*nobdeps*::
Omit build dependencies (BDEPEND).

*novdb*::
Omit the installed-package database

*emptydev*::
Do not populate `/dev` with static device nodes.


RECIPE-FILE EXAMPLE
-------------------

   nobdeps
   atoms eix gentoolkit netcat6
   addfiles /var/lib/layercake/stager/helperFiles


EXIT STATUS
-----------
[horizontal]
*0*:: Success
*1*:: Failure


COPYING
-------
Copyright © 2022 Michael Thompson

https://github.com/potano/layercake

SPDX-License-Identifier: GPL-2.0-or-later


SEE ALSO
--------
layercake(1)


